export {default as HeaderPart} from './HeaderPart.vue'
export {default as CartSideBar} from './CartSideBar.vue'
export {default as FooterPart} from './FooterPart.vue'
export {default as LoginModal} from './LoginModal.vue'
export {default as MobileMenu} from './MobileMenu.vue'
export {default as NavBar} from './NavBar.vue'
export {default as NewsLetter} from './NewsLetter.vue'